-- Neovim Keymaps Configuration
--
-- This configuration uses LazyVim, which provides sensible defaults.
-- Default keymaps: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
--
-- Add your custom keymaps below to override defaults or add new bindings.
-- Keymaps are automatically loaded on the VeryLazy event.
--
-- Example custom keymaps:
-- vim.keymap.set("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file" })
-- vim.keymap.set("n", "<leader>q", "<cmd>q<cr>", { desc = "Quit" })
